### ISSUE TITLE
Keycloak no longer supports redirect_uri

### ISSUE THREAD

**Issue by jerrac** [juanfont/headscale#1204]
**Bug description**
Authenticating to Keycloak fails with a "Invalid parameter: redirect_uri" message

**To Reproduce**
* Configure a Keycloak 20.0.1 server, realm, and client.
* Configure Headscale to use it.
* Try to authenticate Headscale.

**Context info**
- Version of headscale used: 0.30.0
- Version of tailscale client: Android 1.30.0
- OS: Headscale server is running off the official Docker image on an Ubuntu 22.04 server.
- The relevant config parameters you used
```yaml
oidc:
  issuer: "https://< my keycloak instance >/realms/< my realm >"
  client_id: "< the client id I configured for headscale >"
  client_secret: "< the secret from keycloak >"
  allowed_groups:
    - /headscale
```

According to [these docs](https://www.keycloak.org/docs/latest/upgrading/index.html#openid-connect-logout) "The parameter redirect_uri is no longer supported"

Today is the first time I've tried anything with headscale, and I'm no Keycloak expert, but that doc page seems fairly cut and dried, so I thought I'd at least give you a heads up about it since I didn't find anything about it when I searched. 

Now, back to figuring out how to use headscale... :)
