### ISSUE TITLE
Private key not creating

### ISSUE THREAD

**Issue by magf** [juanfont/headscale#1209]
**Can't start SystemD daemon with first generating private key**

After creating user/group, all needed folders, creating SystemD unit and try to start with `systemctl start headscale`:

```bash
INF No private key file at path, creating... path=/etc/headscale/private.key
FTL home/runner/work/headscale/headscale/cmd/headscale/cli/server.go:21 > Error initializing error="failed to read or create private key: failed to save private key to disk: open /etc/headscale/private.key: read-only file system"
```

All file permissions are met:

```bash
# sudo -u headscale ls -la /etc/headscale
total 20
drwxr-xr-x  2 headscale headscale  4096 Feb  9 08:50 .
drwxr-xr-x 93 root      root       4096 Feb  8 16:28 ..
-rw-r--r--  1 headscale headscale 11514 Feb  8 16:33 config.yaml
-rw-rw-r--  1 headscale headscale     0 Feb  9 08:50 test

# sudo -u headscale ls -la /var/lib/headscale
total 20
drwxr-x---  2 headscale headscale 4096 Feb  9 08:55 .
drwxr-xr-x 39 root      root      4096 Feb  8 16:27 ..
-rw-r--r--  1 headscale headscale  220 Jan  6  2022 .bash_logout
-rw-r--r--  1 headscale headscale 3771 Jan  6  2022 .bashrc
-rw-r--r--  1 headscale headscale  807 Jan  6  2022 .profile
-rw-r--r--  1 headscale headscale    0 Feb  9 08:26 db.sqlite

```

**To Reproduce**

My Ansible playbook:

```yaml
--
- hosts: my-host
  become: yes

  vars:
# Application
    arch: amd64
    headscale_version: '0.20.0'
# Configuration

  tasks:
  - name: Download headscale v{{ headscale_version }} && Make headscale executable
    ansible.builtin.get_url:
      url: 'https://github.com/juanfont/headscale/releases/download/v{{ headscale_version }}/headscale_{{ headscale_version }}_linux_{{ arch }}'
      dest: /usr/local/bin/headscale
      mode: '0755'

  - name: Create headscale group
    group:
      name: headscale
      state: present

  - name: Create headscale service account
    ansible.builtin.user:
      name: headscale
      group: headscale
      home: /var/lib/headscale
      shell: /usr/bin/nologin
      system: true

  - name: Prepare a directory to hold headscale configuration
    ansible.builtin.file:
      path: /etc/headscale
      state: directory
      mode: '0755'
      owner: headscale
      group: headscale

  - name: Create configuration from the template
    ansible.builtin.template:
      src: headscale_config.yaml.j2
      dest: /etc/headscale/config.yaml
      mode: '0644'
      owner: headscale
      group: headscale
    notify:
    - Restart service headscale

  - name: Create an empty SQLite database
    ansible.builtin.file:
      path: /var/lib/headscale/db.sqlite
      state: touch
      mode: '0644'
      owner: headscale
      group: headscale

  - name: Create a SystemD headscale.service configuration
    ansible.builtin.copy:
      src: headscale.service
      dest: /etc/systemd/system/headscale.service
    notify:
    - SystemD reread configs
    - Enable and start service headscale

  handlers:
  - name: SystemD reread configs
    ansible.builtin.systemd:
      daemon_reload: true

  - name: Enable and start service headscale
    ansible.builtin.systemd:
      name: headscale
      state: started
      enabled: true
      masked: no

  - name: Restart service headscale
    ansible.builtin.systemd:
      name: headscale
      state: restarted
```

**Context info**

```bash
uname -a
Linux my-host 5.15.0-58-generic #64-Ubuntu SMP Thu Jan 5 11:43:13 UTC 2023 x86_64 x86_64 x86_64 GNU/Linux

ansible-playbook --version
ansible-playbook [core 2.14.2]
  config file = /home/ansible/.ansible.cfg
  configured module search path = ['/home/ansible/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /home/ansible/.local/lib/python3.10/site-packages/ansible
  ansible collection location = /home/ansible/.ansible/collections:/usr/share/ansible/collections
  executable location = /home/ansible/.local/bin/ansible-playbook
  python version = 3.10.6 (main, Nov 14 2022, 16:10:14) [GCC 11.3.0] (/usr/bin/python3)
  jinja version = 3.1.2
  libyaml = True
```

Configuration files from playbook archived and attached - [headscale_config.tar.gz](https://github.com/juanfont/headscale/files/10695509/headscale_config.tar.gz)
