### ISSUE TITLE
Unable to ssh with tailscale

### ISSUE THREAD

**Issue by Frankzhang854** [juanfont/headscale#1303]
Please ask, I have enabled tailscale ssh on one of the headscale clients, and headscale is also configured with ACL. I don’t know why it still prompts Permission denied (tailscale)

```
acls:
  - action: accept
    src:
      - "frank"
    dst:
      - "*:*"
      - "frankxin:*"
  - action: accept
    src:
      - "frankxin"
    dst:
      - "frankxin:*"
ssh:
  - action: check
    src:
      - "frank"
    dst:
      - "*:*"
      - "frankxin:*"
    user:
      - "some-allowlisted-user"
    checkPeriod: 8h
  - action: check
    src:
      - "frankxin"
    dst:
      - "*:*"
      - "frank:*"
    user:
      - "some-allowlisted-user"
    checkPeriod: 8h
disableIPv4: false
randomizeClientPort: false
```

Version of headscale used: v0.21.0
Version of tailscale client: 1.38.2
OS (e.g. Linux, Mac, Cygwin, WSL, etc.) and version: macOS Ventura
