### ISSUE TITLE
Feature: kubernets operator for headscale

### ISSUE THREAD

**Issue by siredmar** [juanfont/headscale#1523]
## Why

With a headscale kubernetes operator it would be easy to manage every headscale resource like users, keys, ... as native kubernetes resources. 

## Description

Below is a very basic example how headscale resources could look like. 

Example for user
```
apiVersion: headscale.io/v1alpha1
kind: User
spec:
  name: "myuser"
```

Example for preauthkey
```
apiVersion: headscale.io/v1alpha1
kind: PreAuthKey
spec:
  config:
    user: "myuser"
    ephemeral: true
    reusable: true
    expiration: "1h"
  output:
    secretName: mysecret
    secretKey: mykey
```

If i would write an operator for headscale, i'd use crossplane (https://docs.crossplane.io/latest/concepts/providers/)
