### ISSUE TITLE
node in exit-node mode not forwarding traffic to same network which belongs external interface

### ISSUE THREAD

**Issue by winterheart** [juanfont/headscale#1637]
## Bug description

I have two nodes in headscale/tailscale network, one of them is exit-node with external IP:

node1 (exit-node):
* Internal IP: 10.1.0.2/24, External IP: 88.88.88.2/24

node2 (client)
* Internal IP 10.2.0.2/24

When I try use node1 as exit-node, it works as expected except that fact I cannot access to any IP address of external subnet 88.88.88.0/24 (same network for node1):

```
ping -c1 88.88.88.3 # OK
ping -c1 8.8.8.8 # OK, any other external IP
tailscale up --exit-node=node1 --accept-routes --login-server=https://vpn.example.com
ping -c1 88.88.88.3 # FAIL, no response
ping -c1 8.8.8.8 # Still OK
```
After switch to exit-node there no any traffic on `tailscale0` interface on node1 related to 88.88.88.3, but any other external traffic from node2 to the Internet goes without any problems.

## Environment

* headscale v0.22.3
* tailscale 1.50.1-ERR-BuildInfo
* OS Linux on both clients, kernel 6.1.*

Exit node has `-A POSTROUTING -o tailscale0 -j MASQUERADE` iptables rule in nat table.

ACL related to exit-nodes (user in `admins` and `exitpoints` groups, node1 has `exitpoints` tag):

```
  - action: accept
    src:
      - group:admins
      - group:exitpoints
    dst:
      - tag:exitpoints:*
      # Ugly list in abscese of autogroup:internet :( https://github.com/juanfont/headscale/issues/657
      - 0.0.0.0/5:*
      - 8.0.0.0/7:*
      - 11.0.0.0/8:*
      - 12.0.0.0/6:*
      - 16.0.0.0/4:*
      - 32.0.0.0/3:*
      - 64.0.0.0/3:*
      - 96.0.0.0/6:*
      - 100.0.0.0/10:*
      - 100.128.0.0/9:*
      - 101.0.0.0/8:*
      - 102.0.0.0/7:*
      - 104.0.0.0/5:*
      - 112.0.0.0/5:*
      - 120.0.0.0/6:*
      - 124.0.0.0/7:*
      - 126.0.0.0/8:*
      - 128.0.0.0/3:*
      - 160.0.0.0/5:*
      - 168.0.0.0/6:*
      - 172.0.0.0/12:*
      - 172.32.0.0/11:*
      - 172.64.0.0/10:*
      - 172.128.0.0/9:*
      - 173.0.0.0/8:*
      - 174.0.0.0/7:*
      - 176.0.0.0/4:*
      - 192.0.0.0/9:*
      - 192.128.0.0/11:*
      - 192.160.0.0/13:*
      - 192.169.0.0/16:*
      - 192.170.0.0/15:*
      - 192.172.0.0/14:*
      - 192.176.0.0/12:*
      - 192.192.0.0/10:*
      - 193.0.0.0/8:*
      - 194.0.0.0/7:*
      - 196.0.0.0/6:*
      - 200.0.0.0/5:*
      - 208.0.0.0/4:*
```

- [ ] Headscale is behind a (reverse) proxy
- [ ] Headscale runs in a container

## To Reproduce

Run two clients, one as exit-node with external interface. Add relevant ACL to allow using exit-node. Enable exit-node on second client and try to access to any IP from exit-node external subnet.
