### ISSUE TITLE
override_local_dns dosent work on maos

### ISSUE THREAD

**Issue by kfkawalec** [juanfont/headscale#1664]
Headscale: 0.22.3
Tailscale (console): 1.56.0

There is no DNS resolver pointing to 100.100.100.100 on MacOS.
Command: tailscale up --accept-dns --accept-routes

```
user@mac ~ % scutil --dns
DNS configuration

resolver #1
  nameserver[0] : 192.168.100.101
  nameserver[1] : 192.168.100.102
  if_index : 15 (en0)
  flags    : Request A records
  reach    : 0x00020002 (Reachable,Directly Reachable Address)

resolver #2
  domain   : local
  options  : mdns
  timeout  : 5
  flags    : Request A records
  reach    : 0x00000000 (Not Reachable)
  order    : 300000

...

resolver #8
  domain   : search.tailscale
  search domain[0] : test.local
  search domain[1] : user1.ts.local
  flags    : Request A records
  reach    : 0x00000000 (Not Reachable)

DNS configuration (for scoped queries)

resolver #1
  nameserver[0] : 192.168.100.101
  nameserver[1] : 192.168.100.102
  if_index : 15 (en0)
  flags    : Scoped, Request A records
  reach    : 0x00020002 (Reachable,Directly Reachable Address)
```

Config:
```
dns_config:
  override_local_dns: true

  nameservers:
    - 1.1.1.1

  restricted_nameservers:
    test.local:
      - 10.10.0.1
  domains: ["test.local"]
 
  magic_dns: true

  base_domain: ts.local
```

Logs:
```
LinkChange: major, rebinding. New state: interfaces.State{defaultRoute=en0 ifs={en0:[192.168.100.59/24 llu6] utun4:[100.64.0.1/32 fd7a:115c:a1e0::1/128 llu6]} v4=true v6=false}
dns: Set: {DefaultResolvers:[1.1.1.1] Routes:{dev.ts.local.:[] test.local.:[10.10.0.1] users.ts.local.:[] users.ts.local.:[]}+65arpa SearchDomains:[test.local. users.ts.local.] Hosts:3}
dns: Resolvercfg: {Routes:{.:[1.1.1.1] test.local.:[10.10.0.1]} Hosts:3 LocalDomains:[users.ts.local.]+65arpa}
dns: OScfg: {Nameservers:[100.100.100.100] SearchDomains:[test.local. users.ts.local.] }
wgengine: set DNS config again after major link change
```
