### ISSUE TITLE
Two nodes appear repeatedly

### ISSUE THREAD

**Issue by flyzstu** [juanfont/headscale#1686]
## Bug description

Recently I encountered a problem. I used docker-compose to set up headscale and tailscale, and used a reusable key to enable the built-in derp server. Every time the docker service is restarted, headscale gets a new tailscale node, which is not as expected. The expectation should be that the node should not change every time it is restarted.

## Environment

- OS: Linux Debian 12 
- Headscale version: 0.23.0-alpha2
- Tailscale version:  v1.56.1 
- Kernel version:  6.1.0-17-amd64

- [ ] Headscale is behind a (reverse) proxy
- [x] Headscale runs in a container

## To Reproduce

1. docker-compose.yml
```yml
services:
  headscale:
    image: headscale/headscale:0.23.0-alpha2
    container_name: headscale
    hostname: headscale
    network_mode: host
    volumes:
      - ./headscale:/etc/headscale
    environment:
      - TZ=Asia/Shanghai   
    restart: always
    stop_grace_period: 2m
    command: headscale serve
  tailscale:
      hostname: tailscale
      container_name: tailscale
      image: tailscale/tailscale:v1.56.1
      environment:
        - TS_EXTRA_ARGS=--login-server=https:/domain:444 --accept-routes=false --accept-dns=false --advertise-routes=192.168.100.0/24 --authkey=token
        - TZ=Asia/Shanghai
      volumes:
        - /var/run/tailscale:/var/run/tailscale
        - ./tailscale:/var/lib
      devices:
        - /dev/net/tun:/dev/net/tun:rwm
      cap_add:
        - net_admin
        - sys_module
      restart: unless-stopped
      depends_on:
        headscale:
          condition: service_started
      networks:
        - default
networks:
  default:
    name: tailscale
    external: true
```

2. my headscale config
```yml

server_url: https://domain:444
listen_addr: 0.0.0.0:444
metrics_listen_addr: 127.0.0.1:9090
grpc_listen_addr: 127.0.0.1:50443
grpc_allow_insecure: false
noise:
  private_key_path: /etc/headscale/noise_private.key
ip_prefixes:
  - 100.64.0.0/10
derp:
  server:
    enabled: true
    region_id: 999
    region_code: "headscale"
    region_name: "Headscale Embedded DERP"
    stun_listen_addr: "0.0.0.0:3478"
    private_key_path: /etc/headscale/private.key
  urls:
    # - https://controlplane.tailscale.com/derpmap/default
  # paths:
  #   - /etc/headscale/derp-example.yaml
  paths: []
  auto_update_enabled: true
  update_frequency: 24h
disable_check_updates: false
ephemeral_node_inactivity_timeout: 30m
node_update_check_interval: 10s
db_type: sqlite3
db_path: /etc/headscale/db.sqlite
acme_url: https://acme-v02.api.letsencrypt.org/directory
acme_email: ""

tls_letsencrypt_hostname: ""
tls_letsencrypt_challenge_type: HTTP-01
tls_letsencrypt_listen: ":http"
tls_cert_path: "/etc/headscale/fullchain.cer"
tls_key_path: "/etc/headscale/domain.key"
log:
  format: text
  level: info
acl_policy_path: ""
dns_config:
  override_local_dns: false

  nameservers:
    - 119.29.29.29

  domains: []
  magic_dns: false


  base_domain: arpa
unix_socket: /var/run/headscale/headscale.sock
unix_socket_permission: "0770"
logtail:
  # Enable logtail for this headscales clients.
  # As there is currently no support for overriding the log server in headscale, this is
  # disabled by default. Enabling this will make your clients send logs to Tailscale Inc.
  enabled: false

# Enabling this option makes devices prefer a random port for WireGuard traffic over the
# default static port 41641. This option is intended as a workaround for some buggy
# firewall devices. See https://tailscale.com/kb/1181/firewalls/ for more information.
randomize_client_port: true
```
3. command:
```bash
headscale users c fly97
headscale pre create -u fly97 --reusable
# docker compose up -d
headscale node ls
```
![image](https://github.com/juanfont/headscale/assets/94161727/c78c59d4-0a9c-4234-9094-bf6c48cf14e6)
when runs docker compose down and docker compose up; a new node will be in headscale:
```bash
# docker compose down; docker compose up -d
headscale node ls
```
![image](https://github.com/juanfont/headscale/assets/94161727/e2388baa-b486-43a7-9063-72cc5cc0c02b)
Obviously the same node, but two nodes are created. 
What should I do to avoid this?
I would be grateful for your reply!!
