### ISSUE TITLE
about acl

### ISSUE THREAD

**Issue by pope-L** [juanfont/headscale#1714]
my acl.yaml

...
```
  - action: accept
    src:
      - "myu"
    dst:
      - "*:*"
      - "serv:*"
```
  ...

tag serv nodes can't connect to user myu's nodes ,is ok   
myu's nodes cant connect to tag serv's nodes ,is ok
but in taiscale windows client menu Network devices, list the user myu's nodes, How can we prevent these nodes from displaying the names of inaccessible nodes?
