### ISSUE TITLE
Device approval

### ISSUE THREAD

**Issue by SinghNanak** [juanfont/headscale#1757]
## Why

I don't want unauthorized devices connecting to my network.
## Description

https://tailscale.com/kb/1099/device-approval

**Comment by lennartbrandin** [comment]
What is the usecase instead of just keeping default login (your keys / node registration) secure?

**Comment by nsdhanoa** [comment]
It helps when there are multiple users and devices.

**Comment by adriangoransson** [comment]
I agree that this would be helpful to enable OIDC for user management but still approve every new device key manually. For example if the connected oidc account were to be compromised.

**Comment by adriangoransson** [comment]
I forgot that ACLs and tags are kind of powerful, so it is possible to work around this limitation.

```yaml
# Allow all traffic from all nodes tagged with "tag:device-approved".
acls:
  - action: accept
    src:
      - tag:device-approved
    dst:
      - "*:*"

# Tags must be owned. An autogroup seemed appropriate.
https://tailscale.com/kb/1337/acl-syntax#autogroups
tagOwners:
  tag:device-approved:
    - autogroup:owner
```

Approve a new device with
```sh
headscale nodes tag -i <ID> -t tag:device-approved
```

Where you get `<ID>` from `headscale nodes ls [-u <user>]`.
