### ISSUE TITLE
Headscale container keeps restarting

### ISSUE THREAD

**Issue by guilherme-n-l** [juanfont/headscale#1775]
## Bug description

After installing using this docker compose code, I keep getting this in the logs before the container restarts and tries again.

```yaml
version: '3.5'
services:
  headscale:
    image: headscale/headscale:latest
    container_name: headscale
    volumes:
      - {my config directory}:/etc/headscale
    ports:
        - 8181:8181
        - 9090:9090
    command: headscale serve
    restart: unless-stopped
  headscale-ui:
    image: ghcr.io/gurucomputing/headscale-ui:latest
    restart: unless-stopped
    container_name: headscale-ui
    ports:
        - 9999:80
```

```
2024-02-19 00:16:53 Error: unknown command "headscale" for "headscale"
2024-02-19 00:16:53 Run 'headscale --help' for usage.
```

the headscale-ui container works ok.

## Environment

- Version of headscale: latest
- OS: Windows 11 (Docker Desktop)
- Docker version: 4.27.2

- [ ] Headscale is behind a (reverse) proxy
- [x] Headscale runs in a container
