### ISSUE TITLE
headscale docker keep restarting

### ISSUE THREAD

**Issue by Kingwayer** [juanfont/headscale#1967]
### Is this a support request?

- [X] This is not a support request

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

after docker compose up -d, headscale container keep restarting, please referring to 
https://github.com/juanfont/headscale/issues/1775 

### Expected Behavior

keep working after container created.

### Steps To Reproduce

nano docker-compose.yml and in put below then docker compose up -d

```
version: '3.5'
services:
  headscale:
    image: headscale/headscale:0.22.3
    container_name: headscale
    volumes:
      - /var/run/headscale
    ports:
        - 8181:8181
        - 9090:9090
    command: headscale serve
    restart: unless-stopped
  headscale-ui:
    image: ghcr.io/gurucomputing/headscale-ui:latest
    restart: unless-stopped
    container_name: headscale-ui
    ports:
        - 3838:80
```
### Environment

```markdown
- OS: debian12
- Headscale version:0.22.3
- Tailscale version:
```

### Runtime environment

- [ ] Headscale is behind a (reverse) proxy
- [X] Headscale runs in a container

Edit: Add code block

**Comment by Kingwayer** [comment]
> There is currently no docker container with the latest tag.
> 
> Use specific version like `headscale/headscale: 0.22.3` with a command `headscale serve` or a unstable alpha version with `headscale/headscale:0.23.0-alpha12` and a command `serve`.

Thank you, headscale/headscale: 0.22.3 should be headscale/headscale:0.22.3, am I right?

**Comment by Kingwayer** [comment]
> There is currently no docker container with the latest tag.
> 
> Use specific version like `headscale/headscale: 0.22.3` with a command `headscale serve` or a unstable alpha version with `headscale/headscale:0.23.0-alpha12` and a command `serve`.

Actually just did all your mentioned difference version combination, all is the same, can you do a test to verify?

**Comment by ohdearaugustin** [comment]
For 0.22.3 just follow the [docs](https://headscale.net/running-headscale-container/#configure-and-run-headscale)

**Comment by Kingwayer** [comment]
> For 0.22.3 just follow the [docs](https://headscale.net/running-headscale-container/#configure-and-run-headscale)

that's the standard installation step I have followed, you didn't answer to give me any hints at all.

**Comment by Kingwayer** [comment]
@ohdearaugustin  why removed bug label? I think this is a bug and actually after months it's not been fixed yet.

**Comment by ohdearaugustin** [comment]
There is no config file what you are using. There are no logs.
And you claim that you followed the standard installation.

In my opinion this is a user error and not a bug in headscale.
It is a misconfiguration and therefore not a bug.
You reedited the docker-compose.

This docker-compose doesn't look like the one in the documentation.
Sorry, but it seems to me that you don't really understand docker.

**Comment by ohdearaugustin** [comment]
Add your config file and the log output.

**Comment by Kingwayer** [comment]
````
version: "3.7"

services:
  headscale:
    image: headscale/headscale:0.22.3
    restart: unless-stopped
    container_name: headscale
    ports:
      - "0.0.0.0:8080:8080"
      - "127.0.0.1:9090:9090"
    volumes:
      # pls change [config_path] to the fullpath of the config folder just created
      - /opt/headscale:/etc/headscale
    command: headscale serve


headscale-ui:
    image: ghcr.io/gurucomputing/headscale-ui:latest
    restart: unless-stopped
    container_name: headscale-ui
    ports:
        - 3838:80
        -
```

docker log

````
2024-06-05T13:12:39Z FTL go/src/headscale/cmd/headscale/cli/root.go:48 > Error loading config error="fatal error reading config file: Config File \"config\" Not Found in \"[/etc/headscale /root/.headscale /]\""
2024-06-05T13:12:53Z WRN Failed to read configuration from disk error="Config File \"config\" Not Found in \"[/etc/headscale /root/.headscale /]\""
2024-06-05T13:12:53Z FTL go/src/headscale/cmd/headscale/cli/root.go:48 > Error loading config error="fatal error reading config file: Config File \"config\" Not Found in \"[/etc/headscale /root/.headscale /]\""
2024-06-05T13:13:19Z WRN Failed to read configuration from disk error="Config File \"config\" Not Found in \"[/etc/headscale /root/.headscale /]\""
2024-06-05T13:13:19Z FTL go/src/headscale/cmd/headscale/cli/root.go:48 > Error loading config error="fatal error reading config 
````

**Comment by eMoonT** [comment]
You can refer to my configuration, which might provide you with some help.

```yaml
version: '3.7'
services:
  headscale:
    image: headscale/headscale:0.23.0-alpha9
    container_name: headscale
    volumes:
      - ./config:/etc/headscale/
      - /var/run/headscale
    ports:
      - 8080:8080
      - 9090:9090
    command: serve
    restart: always
```
