### ISSUE TITLE
 ERR Could not load DERP servers map file error="open : no such file or directory" path=

### ISSUE THREAD

**Issue by a1ad** [juanfont/headscale#201]
I keep getting this error.

Files in /etc/headscale:
<img width="448" alt="image" src="https://user-images.githubusercontent.com/29516835/138736879-8d160a9e-e43d-4c3d-8761-fedc115e1f9e.png">

Path in config:
<img width="441" alt="image" src="https://user-images.githubusercontent.com/29516835/138736963-aa7d1966-92b3-4028-b980-42e25565a264.png">

Derp.yaml:

```
root@headscale:/etc/headscale# cat derp.yaml 
regions:
  1:
    regionid: 1
    regioncode: nyc
    regionname: New York City
    nodes:
      - name: 1a
        regionid: 1
        hostname: derp1.tailscale.com
        ipv4: 159.89.225.99
        ipv6: 2604:a880:400:d1::828:b001
      - name: 1b
        regionid: 1
        hostname: derp1b.tailscale.com
        ipv4: 45.55.35.93
        ipv6: 2604:a880:800:a1::f:2001
  10:
    regionid: 10
    regioncode: sea
    regionname: Seatle
    nodes:
      - name: 10a
        regionid: 10
        hostname: derp10.tailscale.com
        ipv4: 137.220.36.168
        ipv6: 2001:19f0:8001:2d9:5400:2ff:feef:bbb1
  11:
    regionid: 11
    regioncode: sao
    regionname: São Paulo
    nodes:
      - name: 11a
        regionid: 11
        hostname: derp11.tailscale.com
        ipv4: 18.230.97.74
        ipv6: 2600:1f1e:ee4:5611:ec5c:1736:d43b:a454
  12:
    regionid: 12
    regioncode: nyc
    regionname: Chicago
    nodes:
      - name: 12a
        regionid: 12
        hostname: derp12.tailscale.com
        ipv4: 216.128.144.130
        ipv6: 2001:19f0:5c01:289:5400:3ff:fe8d:cb5e
      - name: 12b
        regionid: 12
        hostname: derp12b.tailscale.com
        ipv4: 45.63.71.144
        ipv6: 2001:19f0:5c01:48a:5400:3ff:fe8d:cb5f
      - name: 12c
        regionid: 12
        hostname: derp12c.tailscale.com
        ipv4: 149.28.119.105
        ipv6: 2001:19f0:5c01:2cb:5400:3ff:fe8d:cb60
  2:
    regionid: 2
    regioncode: sfo
    regionname: San Francisco
    nodes:
      - name: 2a
        regionid: 2
        hostname: derp2.tailscale.com
        ipv4: 167.172.206.31
        ipv6: 2604:a880:2:d1::c5:7001
      - name: 2b
        regionid: 2
        hostname: derp2b.tailscale.com
        ipv4: 64.227.106.23
        ipv6: 2604:a880:4:1d0::29:9000
  3:
    regionid: 3
    regioncode: sin
    regionname: Singapore
    nodes:
      - name: 3a
        regionid: 3
        hostname: derp3.tailscale.com
        ipv4: 68.183.179.66
        ipv6: 2400:6180:0:d1::67d:8001
  4:
    regionid: 4
    regioncode: fra
    regionname: Frankfurt
    nodes:
      - name: 4c
        regionid: 4
        hostname: derp4c.tailscale.com
        ipv4: 134.122.77.138
        ipv6: 2a03:b0c0:3:d0::1501:6001
      - name: 4d
        regionid: 4
        hostname: derp4d.tailscale.com
        ipv4: 134.122.94.167
        ipv6: 2a03:b0c0:3:d0::1501:b001
      - name: 4e
        regionid: 4
        hostname: derp4e.tailscale.com
        ipv4: 134.122.74.153
        ipv6: 2a03:b0c0:3:d0::29:9001
  5:
    regionid: 5
    regioncode: syd
    regionname: Sydney
    nodes:
      - name: 5a
        regionid: 5
        hostname: derp5.tailscale.com
        ipv4: 103.43.75.49
        ipv6: 2001:19f0:5801:10b7:5400:2ff:feaa:284c
  6:
    regionid: 6
    regioncode: blr
    regionname: Bangalore
    nodes:
      - name: 6a
        regionid: 6
        hostname: derp6.tailscale.com
        ipv4: 68.183.90.120
        ipv6: 2400:6180:100:d0::982:d001
  7:
    regionid: 7
    regioncode: tok
    regionname: Tokyo
    nodes:
      - name: 7a
        regionid: 7
        hostname: derp7.tailscale.com
        ipv4: 167.179.89.145
        ipv6: 2401:c080:1000:467f:5400:2ff:feee:22aa
  8:
    regionid: 8
    regioncode: lhr
    regionname: London
    nodes:
      - name: 8b
        regionid: 8
        hostname: derp8b.tailscale.com
        ipv4: 46.101.74.201
        ipv6: 2a03:b0c0:1:d0::ec1:e001
      - name: 8c
        regionid: 8
        hostname: derp8c.tailscale.com
        ipv4: 206.189.16.32
        ipv6: 2a03:b0c0:1:d0::e1f:4001
      - name: 8d
        regionid: 8
        hostname: derp8d.tailscale.com
        ipv4: 178.62.44.132
        ipv6: 2a03:b0c0:1:d0::e08:e001
  9:
    regionid: 9
    regioncode: dfw
    regionname: Dallas
    nodes:
      - name: 9a
        regionid: 9
        hostname: derp9.tailscale.com
        ipv4: 207.148.3.137
        ipv6: 2001:19f0:6401:1d9c:5400:2ff:feef:bb82
      - name: 9b
        regionid: 9
        hostname: derp9b.tailscale.com
        ipv4: 144.202.67.195
        ipv6: 2001:19f0:6401:eb5:5400:3ff:fe8d:6d9b
      - name: 9c
        regionid: 9
        hostname: derp9c.tailscale.com
        ipv4: 155.138.243.219
        ipv6: 2001:19f0:6401:fe7:5400:3ff:fe8d:6d9c`
```
