### ISSUE TITLE
[Bug] 0.23.0-beta1 breaks DNS custom nameservers

### ISSUE THREAD

**Issue by MitchTalmadge** [juanfont/headscale#2026]
### Is this a support request?

- [X] This is not a support request

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

After upgrading from 0.23.0-alpha12 to 0.23.0-beta1, with no other changes at all, queries made to `100.100.100.100` which should use a listed `nameserver` give `status: NXDOMAIN`. 

![image](https://github.com/user-attachments/assets/541ba528-44c6-4961-a375-0013a45fc9e5)

### Expected Behavior

Queries should return results from the `nameservers`

![image](https://github.com/user-attachments/assets/31b4651c-a43d-4f88-a7db-485e9c27a8f9)

### Steps To Reproduce

I use the following DNS config:

```
dns_config:
  override_local_dns: true
  nameservers:
    - 100.64.0.6
  restricted_nameservers:
    foo.bar: # Redacted
      - 100.64.0.2
    baz.foo: # Redacted
      - 100.64.0.2
  domains: []
  magic_dns: true
  base_domain: lorem.ipsum # Redacted
```

On alpha9, 10, 11, and 12, it works fine. On beta1, it fails.

### Environment

```markdown
- OS: Unraid 6.12.10, running Docker 24.0.9
- Headscale version: 0.23.0-beta1
- Tailscale version: 1.70.0 on MacOS Sonoma
```

### Runtime environment

- [X] Headscale is behind a (reverse) proxy
- [X] Headscale runs in a container
