### ISSUE TITLE
tailscale-private    | 2024/08/04 15:49:08 control: NetInfo: NetInfo{varies=true hairpin= ipv6=false ipv6os=true udp=true icmpv4=false derp=#900 portmap= link="" firewallmode="ipt-default"}

### ISSUE THREAD

**Issue by captainstdin** [juanfont/headscale#2043]
### Is this a support request?

- [X] This is not a support request

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

When I use  Tailscale.com 

tailscale   |  control: NetInfo: NetInfo{varies=false hairpin= ipv6=true ipv6os=true udp=true icmpv4=false derp=#7 portmap= link="" firewallmode="ipt-default"}

but 

When I use  headscale , It happened `hairpin= ipv6=false`

tailscale-private    | 2024/08/04 15:49:08 control: NetInfo: NetInfo{varies=true hairpin= ipv6=false ipv6os=true udp=true icmpv4=false derp=#900 portmap= link="" firewallmode="ipt-default"}

curl -4  myheadscale.domain:8080   ok
curl -6  myheadscale.domain:8080   ok

my headscale server both enable ipv4/ipv6 ,and  http request both ok

### Expected Behavior

Enable ipv6

### Steps To Reproduce

```yaml
version: "3.7"
services:
  tailscale-private:
    image: tailscale/tailscale:latest
    container_name:  tailscale-private
    environment:
      - TS_AUTHKEY=d214ea81********5382d367eeee1bfd412
      - TS_STATE_DIR=/var/lib/tailscale
      - TS_ROUTES=192.168.3.0/24
      - TS_HOSTNAME=HomeOrangePI
      - TS_USERSPACE=false
      - TS_EXTRA_ARGS=  --login-server=https://mytailscale.com
    volumes:
      - ./tailscale-nginx/state:/var/lib/tailscale
      - /dev/net/tun:/dev/net/tun
    cap_add:
      - net_admin
      - sys_module
    restart: unless-stopped
    sysctls:
      - net.ipv6.conf.all.disable_ipv6=0
    network_mode: bridge
  nginx:
    image: nginx
    depends_on:
      - tailscale-private
    network_mode: service:tailscale-private
```

### Environment

```markdown
- OS:
headscale serverOS
NAME="CentOS Linux"
VERSION="7 (Core)"
ID="centos"
ID_LIKE="rhel fedora"
VERSION_ID="7"
PRETTY_NAME="CentOS Linux 7 (Core)"
ANSI_COLOR="0;31"

- Headscale version:

 headscale/headscale:0.23.0-beta1

- Tailscale version:
 docker exec -it tailscale-private tailscale version
1.70.0
  tailscale commit: d601f16e1b676b11902ee5d71e6042d95fb09252
  go version: go1.22.5

 Program starting: v1.70.0-td601f16e1
```

### Runtime environment

- [ ] Headscale is behind a (reverse) proxy
- [X] Headscale runs in a container
