### ISSUE TITLE
[Bug] New Config.yaml ACL section does not work - Must use old acl_policy_path

### ISSUE THREAD

**Issue by W1BTR** [juanfont/headscale#2055]
### Is this a support request?

- [X] This is not a support request

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

On the beta and alphas, the new config structure for enabling acls looks like this:

```
## Policy
# headscale supports Tailscale's ACL policies.
# Please have a look to their KB to better
# understand the concepts: https://tailscale.com/kb/1018/acls/
policy:
  # The mode can be "file" or "database" that defines
  # where the ACL policies are stored and read from.
  mode: file
  # If the mode is set to "file", the
  # path to a file containing ACL policies.
  # The file can be in YAML or HuJSON format.
  path: "/etc/headscale/acls.json"
```

However, this does not do anything. Instead, one must use the old config line: `acl_policy_path: ""` somewhere in the config (I put mine right under).

### Expected Behavior

the ACL file is applied

### Steps To Reproduce

1. Create and enable an ACL file
2. Nothing happens in the logs.

### Environment

```markdown
- OS:Ubuntu 24.04
- Headscale version: 0.23.0-alpha-12 and 0.23.0-beta1
```

### Runtime environment

- [X] Headscale is behind a (reverse) proxy
- [X] Headscale runs in a container
