### ISSUE TITLE
[Bug] NextDNS does not work in 0.23.0-beta2

### ISSUE THREAD

**Issue by mitchellkellett** [juanfont/headscale#2064]
### Is this a support request?

- [X] This is not a support request

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Since upgrading to 0.23.0-beta2 from 0.23.0-beta1, I now get this error in the logs.

2024-08-20T21:03:53Z WRN Invalid global nameserver "https://dns.nextdns.io/abc123". Parsing error: ParseAddr("https://dns.nextdns.io/abc123"): each colon-separated field must have at least one digit (at "https://dns.nextdns.io/abc123") ignoring

### Expected Behavior

NextDNS continues to work like versions prior to 0.23.0-beta2.

### Steps To Reproduce

1. Update config.yaml as per the new format.
2. Start Headscale 0.23.0-beta2.
3. Review logs.

### Environment

```markdown
- OS: Ubunutu 22.04
- Headscale version: 0.23.0-beta2
- Tailscale version: 1.70.0
```

### Runtime environment

- [X] Headscale is behind a (reverse) proxy
- [X] Headscale runs in a container

### Anything else?

config.yaml

```
~~~
dns:
  magic_dns: true
  base_domain: hs.net
  nameservers:
    global:
      - https://dns.nextdns.io/abc123
  search_domains: []
  extra_records: []
~~~
```
