### ISSUE TITLE
[Bug] ERROR: Failed to extract ServerMetadata from context

### ISSUE THREAD

**Issue by madhathacker** [juanfont/headscale#2130]
### Is this a support request?

- [X] This is not a support request

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

I am running Headscale in a docker container. For some reason after editing the `config.yaml` while Headscale was running, I start getting spammed with the error `ERROR: Failed to extract ServerMetadata from context` in the Docker logs. Restarting the service doesn't seem to stop this. I am also running `headscale-ui` and `headscale-admin` but I don't think they are the problem here.

### Expected Behavior

Edit the config while the server is running.

### Steps To Reproduce

1. Start Headscale container.
2. From docker host, open the config.yaml
3. Make a change and write it to the config file

### Environment

```markdown
- OS: Ubuntu 22.04.4 LTS
- Docker: Version 25.0.3, build 4debf41
- Headscale version: headscale/headscale:v0.23.0-alpha12
```

### Runtime environment

- [X] Headscale is behind a (reverse) proxy
- [X] Headscale runs in a container

### Anything else?

I was simply trying to add OIDC to headscale by editing the config.

**Comment by kradalby** [comment]
Can you please try the latest beta, and ensure that the CLI binary and the server binary is the same version?

**Comment by agarzon-orangerine** [comment]
I see the same error, Im using docker image: headscale/headscale:0.23.0-rc.1 (latest at this moment)

My compose is quite straight forward:

```yml
services:
  headscale:
    image: headscale/headscale:0.23.0-rc.1
    restart: unless-stopped
    container_name: headscale
    environment:
      - TZ=America/Toronto
    volumes:
      - ./conf:/etc/headscale
      - headscale_data:/var/lib/headscale
    command: serve
    labels:
      - traefik.enable=true
      - traefik.http.routers.${COMPOSE_PROJECT_NAME}_headscale.rule=Host(`${DOMAIN}`)
      - traefik.http.routers.${COMPOSE_PROJECT_NAME}_headscale.tls=true
      - traefik.http.services.${COMPOSE_PROJECT_NAME}_headscale.loadbalancer.server.port=8080
      
volumes:
  headscale_data:

networks:
  default:
    external: true
    name: proxy

```
