### ISSUE TITLE
[Bug] authURL is empty when using GitHub as an OIDC server

### ISSUE THREAD

**Issue by maxpain** [juanfont/headscale#2168]
### Is this a support request?

- [X] This is not a support request

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Headscale redirects to empty [authURL](https://github.com/juanfont/headscale/blob/95150401612ec5143f5d9d44bcfa8730bcf94bba/hscontrol/oidc.go#L169C2-L169C9)

```
2024-10-03T11:08:53Z DBG Redirecting to ?client_id=123&domain_hint=...
```

### Expected Behavior

Headscale should redirect to "https://github.com/login/oauth/authorize"

### Steps To Reproduce

1. Create an OAuth app in GitHub developer settings
2. Set up Headscale to use GitHub as an OIDC server:

```yaml
oidc:
  only_start_if_oidc_is_available: true
  issuer: "https://token.actions.githubusercontent.com"
  client_id: "123"
  client_secret: "123"
```

3. Try to login

### Environment

```markdown
- OS: Ubuntu 24.04
- Headscale version: 0.23.0
```

### Runtime environment

- [ ] Headscale is behind a (reverse) proxy
- [X] Headscale runs in a container
