### ISSUE TITLE
[Bug] Tailscale Client Fails to Resolve DNS

### ISSUE THREAD

**Issue by W1BTR** [juanfont/headscale#2209]
### Is this a support request?

- [X] This is not a support request

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Seems more like a Tailscale bug, but the Tailscale client on Windows often fails to connect on startup. It's stuck on "connecting..." despite my machine having an active Ethernet connection.

In the logs, it says it's failing to resolve my headscale server's domain, but my dns servers (8.8.8.8 and 8.8.4.4) passed to me from my router work fine, and I can properly ping all common dns servers from cmd. I can also browse the internet just fine. I can also visit the domain for my headscale server just fine, and ping it properly.

```
2024-10-23T09:26:25.779-04:00: [v1] v1.76.3-t02acaa00e-g551df6588 peers: 37569296/7424000 1080/248 2128/4636 109014776/59720396
2024-10-23T09:26:26.190-04:00: control: trying bootstrapDNS("derp16d.tailscale.com", "2607:f740:17::475") for "headscale.mydomain.com" ...
2024-10-23T09:26:26.225-04:00: control: bootstrapDNS("derp16d.tailscale.com", "2607:f740:17::475") for "headscale.mydomain.com" error: Get "https://derp16d.tailscale.com/bootstrap-dns?q=headscale.mydomain.com": dial tcp [2607:f740:17::475]:443: connectex: A socket operation was attempted to an unreachable network.
2024-10-23T09:26:26.226-04:00: control: [v1] TryLogin: fetch control key: Get "https://headscale.mydomain.com/key?v=106": failed to resolve "headscale.mydomain.com": no DNS fallback candidates remain for "headscale.mydomain.com"
2024-10-23T09:26:26.226-04:00: control: [v1] sendStatus: authRoutine-report: state:authenticating
2024-10-23T09:26:26.226-04:00: control: authRoutine: [v1] backoff: 25712 msec
2024-10-23T09:26:26.226-04:00: Received error: fetch control key: Get "https://headscale.mydomain.com/key?v=106": failed to resolve "headscale.mydomain.com": no DNS fallback candidates remain for "headscale.mydomain.com"
```
_Note that I changed to domain for privacy._

I can sometimes get it going by disconnecting and reconnecting my internet after restarting the Tailscale service.

### Expected Behavior

I'd expect it to connect right away using the DNS from my host machine. It almost looks like it's trying to use the tailscale magic dns, but that wont work since it's not running yet.

### Steps To Reproduce

Not sure what's unique about my environment, but all I can think of:

1. Using ethernet with another secondary ethernet adapter and wifi enabled but not in use
2. Start Windows

### Environment

```markdown
- OS: Windows 10
- Headscale version: 0.23.0
- Tailscale version: 1.76.3
```

### Runtime environment

- [X] Headscale is behind a (reverse) proxy
- [X] Headscale runs in a container

### Anything else?

More logs: https://paste.yunohost.org/onebulayar.log

**Comment by hopleus** [comment]
1. What does HeadScale have to do with this if you say the problem is DNS resolution on your machine?
2. Have you tried changing the configuration and connecting to HeadScale without using a domain, but directly by IP?

**Comment by W1BTR** [comment]
For clarification, DNS does work fine for everything other than the Tailscale app, even with the headscale server's domain. 

I do believe it is a bug with the Tailscale app, but the docs for Headscale say to make sure and send all issues, even those with the Tailscale app to the Headscale Github, so I was following that. Every time I restart the Tailscale service, it proceeds to work.

Ill have to try using an IP, I didnt think of that. Will report back.

**Comment by nblock** [comment]
> […] but the docs for Headscale say to make sure and send all issues, even those with the Tailscale app to the Headscale Github, so I was following that.

That should probably be fixed in the docs. Do you have a pointer to the specific section?

**Comment by mastier** [comment]
I encounter the same issue, I got nginx in front of headscale 0.25 and it's passing request to the docker container via let's say mydomain.example.com

When I am connected tailscale to my headscale instance in mydomain.example.com the DNS is 100.100.100.100
```
$ dig vpn.mastier.pl @100.100.100.100

; <<>> DiG 9.18.30-0ubuntu0.24.04.2-Ubuntu <<>> mydomain.example.com @100.100.100.100
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: NXDOMAIN, id: 19081
;; flags: qr aa rd ra ad; QUERY: 1, ANSWER: 0, AUTHORITY: 0, ADDITIONAL: 0

;; QUESTION SECTION:
;vpn.mastier.pl.			IN	A

;; Query time: 0 msec
;; SERVER: 100.100.100.100#53(100.100.100.100) (UDP)
;; WHEN: Fri Feb 21 18:31:24 CET 2025
;; MSG SIZE  rcvd: 32
```

While normally it resolves it via Google DNS

That domain is also magic dns base_domain

```
dns:                                                                                                
  # Whether to use [MagicDNS](https://tailscale.com/kb/1081/magicdns/).                             
  magic_dns: true                                                                                   
                                                                                                    
  # Defines the base domain to create the hostnames for MagicDNS.                                   
  # This domain _must_ be different from the server_url domain.                                     
  # `base_domain` must be a FQDN, without the trailing dot.                                         
  # The FQDN of the hosts will be                                                                   
  # `hostname.base_domain` (e.g., _myhost.example.com_).                                            
  base_domain:  mydomain.example.com 
```

That seems to be an issue here
If I switch to other domain like ts.mydomain.example.com everything works as expected

 dig vpn.mastier.pl @100.100.100.100
```
; <<>> DiG 9.18.30-0ubuntu0.24.04.2-Ubuntu <<>> vpn.mastier.pl @100.100.100.100
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: NOERROR, id: 46541
;; flags: qr rd ra ad; QUERY: 1, ANSWER: 2, AUTHORITY: 0, ADDITIONAL: 1

;; OPT PSEUDOSECTION:
; EDNS: version: 0, flags:; udp: 1232
;; QUESTION SECTION:
;vpn.mastier.pl.			IN	A

;; ANSWER SECTION:
mydomain.example.com		3600	IN	A	83.X.X.X

;; Query time: 92 msec
;; SERVER: 100.100.100.100#53(100.100.100.100) (UDP)
;; WHEN: Fri Feb 21 18:38:12 CET 2025
;; MSG SIZE  rcvd: 73
```
