### ISSUE TITLE
[Feature] Wildcard support for split DNS configuration

### ISSUE THREAD

**Issue by lgrn** [juanfont/headscale#2341]
### Use case

There is a [split attribute](https://github.com/juanfont/headscale/blob/10a72e8d542af68c0c280f2a6ccc84849719b24c/config-example.yaml#L287) in `config-example.yaml` that allows you to configure "_a map of domains and which DNS server to use for each_". In cases of a split VPN scenario, where Headscale is only used to access "internal" resources but not the rest of the Internet, it seems likely that one would want to configure entire domains or subdomains rather than explicit domain names to be passed to a separate DNS.

### Description

Functionality today:

```yaml
  nameservers:
    global:
      - 1.1.1.1
      - 1.0.0.1

    split:
      foo.internal.domain:
        - 10.10.10.10
      bar.internal.domain:
        - 10.10.10.10
```

Feature request:

```yaml
  nameservers:
    global:
      - 1.1.1.1
      - 1.0.0.1

    split:
      *.internal.domain:
        - 10.10.10.10
```

If starting an attribute with `*` causes yaml or other syntax issues, perhaps the syntax `.internal.domain` or similar could be considered instead.

### Contribution

- [ ] I can write the design doc for this feature
- [ ] I can contribute this feature

**Comment by Nathanael-Mtd** [comment]
You can just set ``internal.domain`` to your specified DNS server, every request to that domain or subdomain will be handeled by the specified server.

For example:

```
  nameservers:
    global:
      - 1.1.1.1
      - 1.0.0.1

    split:
      internal.domain:
        - 10.10.10.10
```
