### ISSUE TITLE
Error initializing: open : no such file or directory

### ISSUE THREAD

**Issue by Bpazy** [juanfont/headscale#244]
Error occurred when I tried to run headscale with docker compose.

Here is my operations and error output:
```
root@5dbbd5e70962:/etc/headscale# ls
config.yaml  db.sqlite  derp.json
root@5dbbd5e70962:/etc/headscale# headscale namespaces create myfirstnamespace
2021/12/01 03:17:11 Error initializing: open : no such file or directory
```

The content of `config.yaml`:
```
server_url: http://headscale.example.host
listen_addr: 0.0.0.0:8080
ip_prefix: 192.168.196.0/24
disable_check_updates: true
log_level: debug
derp_map_path: derp.json
db_type: sqlite3
db_path: db.sqlite
ephemeral_node_inactivity_timeout: "30m"
```

The content of `derp.json` is copied from [tailscale sample](https://raw.githubusercontent.com/tailscale/tailscale/main/net/dnsfallback/dns-fallback-servers.json)

And `docker-compose.yaml` with command `sudo docker-compose run --build --force-recreate`:
```yaml
version: '3'
services:
  headscale:
    image: headscale/headscale:latest
    restart: always
    ports:
      - "1333:8080"
    volumes:
      - ./config:/etc/headscale/
    stdin_open: true # docker run -i. For debugging
    tty: true        # docker run -t. For debugging
    command: bash
```
