### ISSUE TITLE
[Bug] Cannot Ban Some Region Derp using Region ID

### ISSUE THREAD

**Issue by panteparak** [juanfont/headscale#2450]
### Is this a support request?

- [x] This is not a support request

### Is there an existing issue for this?

- [x] I have searched the existing issues

### Current Behavior

Currently, there are no ways to exclude some region from the tailscale default derp map from within tailscale. 
It is a non or all through the 

### Expected Behavior

Expected to be able to exclude some region from the predefine derpmap.

Within Tailscale Official Document. It should be achievable like so.
```
{
  // ... other parts of tailnet policy file
  "derpMap": { "Regions": { "1": null } }
}
```
Docs: https://tailscale.com/kb/1118/custom-derp-servers#optional-remove-tailscales-derp-servers

### Steps To Reproduce

Using the derp config similar to my set up below.
Run `tailscale netcheck` to view the nearest available derp nodes

### Environment

```markdown
- OS: Ubuntu 24.04
- Headscale version: 0.24.2
- Tailscale version: 1.80.2 (Mac OSX)
```

### Runtime environment

- [x] Headscale is behind a (reverse) proxy
- [x] Headscale runs in a container

### Anything else?

Headscale Config Snippet
```
derp:
      server:
        enabled: false
        region_id: 999
        region_code: "headscale"
        region_name: "Headscale Embedded DERP"
        stun_listen_addr: "0.0.0.0:3478"
        private_key_path: /var/lib/headscale/derp_server_private.key

        automatically_add_embedded_derp_region: true
        ipv4: 1.2.3.4
        ipv6: 2001:db8::1
      urls:
        - https://controlplane.tailscale.com/derpmap/default
      paths:
        - /etc/tailscale-derp/custom-tailscale-derp-region.yaml
      auto_update_enabled: true
      update_frequency: 1h
```
`custom-tailscale-derp-region.yaml`
```
regions:
  3: {} # null does not work also
  6: {}
  20: {}
  900:
    regionid: 900
    regioncode: sgp1
    regionname: <REDACTED>
    nodes:
      - name: <REDACTED>
        regionid: 900
        hostname: <REDACTED>
        ipv4: <REDACTED>
        ipv6: ""
        stunport: 0
        stunonly: false
        derpport: 0
```

Tailscale Netcheck
```
Report:
	* Time: 2025-02-25T10:50:08.798843Z
	* UDP: true
	* IPv4: yes, 125.24.14.107:42073
	* IPv6: no, but OS has support
	* MappingVariesByDestIP: true
	* PortMapping: UPnP, NAT-PMP, PCP
	* CaptivePortal: false
	* Nearest DERP: Singapore
	* DERP latency:
		- sin: 38.2ms  (Singapore)
		- sgp1: 38.3ms  (Digital Ocean SGP1)
```

**Comment by yangboyd** [comment]
Does the OmitDefaultRegions work?

**Comment by panteparak** [comment]
> Does the OmitDefaultRegions work?

No, doesn't work. I figured it might be a letter casing issue so i try it with some combination of upper and lower cases.


```
OmitDefaultRegions: true
omitdefaultregions: true
omitDefaultRegions: true
regions:
  3: {}
  6: {}
  20: {}
  900:
    regionid: 900
    regioncode: sgp1
    regionname: Digital Ocean SGP1
    nodes:
      - name: <REDACTED>
        regionid: 900
        hostname: <REDACTED>
        ipv4: <REDACTED>
        ipv6: ""
        stunport: 0
        stunonly: false
        derpport: 0
```


But another workaround to achieve `OmitDefaultRegions`, is to set `derp.url` ([Link](https://github.com/juanfont/headscale/blob/main/config-example.yaml#L113-L114)) as empty list. 

Just so we're not off-topic. The goal is, to BAN some derp region in a DERPMap
