### ISSUE TITLE
[Bug] Cannot create preauth keys for users without username

### ISSUE THREAD

**Issue by paapug** [juanfont/headscale#2492]
### Is this a support request?

- [x] This is not a support request

### Is there an existing issue for this?

- [x] I have searched the existing issues

### Current Behavior

When using Google as OIDC it's not possible to create a preshared key. This is because Google does not provide username (as stated by @kradalby in #2333).

### Expected Behavior

The `headscale preauthkeys create` command should fallback to user e-mail (or id) if it cannot find user by username.

### Steps To Reproduce

1. Configure headscale with Google OIDC as per documentation: https://headscale.net/stable/ref/oidc/#google-oauth-example
2. Create a new user via OIDC
```
ID | Name             | Username | Email                            | Created            
1  | My User          |          | my.user@example.com     | 2025-03-19 12:41:30
```
```
- id: 1
  name: ""
  createdat:
    seconds: 1742388090
    nanos: 923918172
  displayname: My User
  email: my.user@example.com
  providerid: <url to https://accounts.google.com>
  provider: oidc
  profilepicurl: <url to https://lh3.googleusercontent.com>
```

3. Try to create a preshared key
```
sudo headscale preauthkeys create  -u my.user@example.com
2025-03-19T13:27:17Z TRC expiration has been set expiration=3600000
Cannot create Pre Auth Key: rpc error: code = Unknown desc = user not found
```
```
sudo headscale preauthkeys create  -u 1
2025-03-19T13:27:17Z TRC expiration has been set expiration=3600000
Cannot create Pre Auth Key: rpc error: code = Unknown desc = user not found
```

### Environment

```markdown
- OS: Debian 12
- Headscale version: 0.25.1
- Tailscale version: N/A
```

### Runtime environment

- [ ] Headscale is behind a (reverse) proxy
- [ ] Headscale runs in a container

### Debug information

```
oidc:
  issuer: "https://accounts.google.com"
  client_id: "<my client id>"
  client_secret: "<my client secret>"
  scope: ["openid", "profile", "email"]
```
