### ISSUE TITLE
[Bug] No exit node

### ISSUE THREAD

**Issue by DevOpsPop** [juanfont/headscale#2497]
### Is this a support request?

- [x] This is not a support request

### Is there an existing issue for this?

- [x] I have searched the existing issues

### Current Behavior

Exit nodes are empty and no access to  `34.160.111.145/32`

```
docker exec headscale headscale routes ls
ID | Node         | Prefix            | Advertised | Enabled | Primary
4  | vpn-2 | 0.0.0.0/0         | true       | false   | -
5  | vpn-2 | ::/0              | true       | false   | -
6  | vpn-2 | 34.160.111.145/32 | true       | true    | true

root@vpn-2:~# docker exec headscale headscale nodes ls
ID | Hostname     | Name         | MachineKey | NodeKey | User     | IP addresses                  | Ephemeral | Last seen           | Expiration          | Connected | Expired
4  | vpn-2        | vpn-2        | [E11Vi]    | [OQu3J] | test     | 100.64.0.5, fd7a:115c:a1e0::5 | false     | 2025-03-21 15:49:57 | N/A                 | online    | no
8  | test         | test         | [CVZ+T]    | [mOo3g] |          | 100.64.0.9, fd7a:115c:a1e0::9 | false     | 2025-03-21 15:56:02 | 2025-09-17 15:50:38 | online    | no
```

### Expected Behavior

Exit nodes aren't empty and access to  `34.160.111.145/32`

### Steps To Reproduce

1. docker compose 

version: "3.7"
```
services:
  headscale:
    image: headscale/headscale:v0.25.1
    restart: unless-stopped
    container_name: headscale
    ports:
      - 8080
      - 9090
    volumes:
      # Please set <HEADSCALE_PATH> to the absolute path
      # of the previously created headscale directory.
      - /root/headscale/config:/etc/headscale
      - /root/headscale/lib:/var/lib/headscale
      - /root/headscale/run:/var/run/headscale
    command: serve
  headscale-ui:
    image: ghcr.io/gurucomputing/headscale-ui:latest
    restart: unless-stopped
    container_name: headscale-ui
    environment:
     - HTTPS_PORT=8443
     - HTTP_PORT=8080
    volumes:
      - /root/Caddyfile:/data/Caddyfile
    ports:
      - 80:8080
      - 443:8443
```
2. create user and authkey 
3. setup exit-node on server
`tailscale up --login-server=https://hs.dev --authkey <>  --advertise-exit-node --advertise-routes=34.160.111.145/32 --reset --force-reauth`
4. login on client
`tailscale up --login-server https://hs.popiplay.dev`

### Environment

```markdown
- OS: client windows11, server linux 22.04
- Headscale version:v0.25.1
- Tailscale version: 1.80.2
```

### Runtime environment

- [ ] Headscale is behind a (reverse) proxy
- [x] Headscale runs in a container

### Debug information

![Image](https://github.com/user-attachments/assets/39cbf913-c274-47d2-a44e-0a75c3e2206f)
