### ISSUE TITLE
[Feature] Round robin for extra_dns

### ISSUE THREAD

**Issue by gawsoftpl** [juanfont/headscale#2499]
### Use case

I have 3 endpoints for master internal kubenetes control plane, and now I can only setup one ip for extra_dns per endpoint.

### Description

round_robin_dns – This allows DNS queries to be distributed across multiple IP addresses (e.g., 100.64.0.3 and 100.64.0.4), providing load balancing (Round Robin DNS).

0.3 and 100.64.0.4), providing load balancing (Round Robin DNS).

extra_records – This section allows you to add custom DNS records. In this case, an A record is added for grafana.myvpn.example.com, which points to two different IP addresses (100.64.0.3 and 100.64.0.4), which will operate in round robin mode.

### Contribution

- [x] I can write the design doc for this feature
- [ ] I can contribute this feature

### How can it be implemented?

```yaml
extra_records:
  - name: "grafana.myvpn.example.com"
    type: "A"
    value: ["100.64.0.3", "100.64.0.4"] 
```
