### ISSUE TITLE
[Bug] headscale documentation regarding docker usage displays outdated information compared to the source code of the page

### ISSUE THREAD

**Issue by xeropresence** [juanfont/headscale#2540]
### Is this a support request?

- [x] This is not a support request

### Is there an existing issue for this?

- [x] I have searched the existing issues

### Current Behavior

If you check visit https://headscale.net/stable/setup/install/container/ you will see following instructions for a docker-compose setup

https://i.imgur.com/WCaZM7p.png

```
version: "3.7"

services:
  headscale:
    image: headscale/headscale:<VERSION>
    restart: unless-stopped
    container_name: headscale
    ports:
      - "127.0.0.1:8080:8080"
      - "127.0.0.1:9090:9090"
    volumes:
      # Please change <CONFIG_PATH> to the fullpath of the config folder just created
      - <CONFIG_PATH>:/etc/headscale
    command: serve


```
If you click view source for this page the contents of the yaml file are

```
    version: "3.7"

    services:
      headscale:
        image: headscale/headscale:<VERSION>
        restart: unless-stopped
        container_name: headscale
        ports:
          - "127.0.0.1:8080:8080"
          - "127.0.0.1:9090:9090"
        volumes:
          # Please set <HEADSCALE_PATH> to the absolute path
          # of the previously created headscale directory.
          - <HEADSCALE_PATH>/config:/etc/headscale
          - <HEADSCALE_PATH>/lib:/var/lib/headscale
          - <HEADSCALE_PATH>/run:/var/run/headscale
        command: serve
 ```

as you can see the currently rendered setting is missing two crucial pieces from the volumes, these missing pieces cause the sqlite database to be reset upon restart.

### Expected Behavior

Correct contents get rendered

### Steps To Reproduce

Visit website

### Environment

```markdown
Chrome
```

### Runtime environment

- [ ] Headscale is behind a (reverse) proxy
- [ ] Headscale runs in a container

### Debug information

N/A
