### ISSUE TITLE
[Bug] autoApprove does not work for 0.0.0.0/0 and ::/0

### ISSUE THREAD

**Issue by spymobilfon** [juanfont/headscale#2568]
### Is this a support request?

- [x] This is not a support request

### Is there an existing issue for this?

- [x] I have searched the existing issues

### Current Behavior

Hello,
I hope you are doing well!

Sorry to bother but I think the fix #2550 did not help and broke workaround.

I was running Tailscale v1.82.5 on a Linux instance and Headscale v0.26.0-beta.1 as a controller on Linux as well.

The Tailscale client was started like this
```
tailscale up --login-server https://hsc.example.org --hostname='router-01' --advertise-exit-node=false --accept-routes=false --accept-dns=false --snat-subnet-routes=true --advertise-tags='tag:routers-vpn,tag:internet-routers' --advertise-routes='10.99.0.0/16,104.16.208.203/32,104.19.159.190/32,10.99.0.2/32'
```
Routers list looks like this
```
ID   | Hostname  | Approved | Available                                                        | Serving (Primary)
2414 | router-01 |          | 10.99.0.0/16, 10.99.0.2/32, 104.16.208.203/32, 104.19.159.190/32 |
```

Then was started with empty advertise routes and again like this
```
tailscale up --login-server https://hsc.example.org --hostname='router-01' --advertise-exit-node=false --accept-routes=false --accept-dns=false --snat-subnet-routes=true --advertise-tags='tag:routers-vpn,tag:internet-routers' --advertise-routes='10.99.0.0/16,104.16.208.203/32,104.19.159.190/32,10.99.0.2/32'
```
Routers list looks like this
```
ID   | Hostname  | Approved                   | Available                                                        | Serving (Primary)
2414 | router-01 | 10.99.0.0/16, 10.99.0.2/32 | 10.99.0.0/16, 10.99.0.2/32, 104.16.208.203/32, 104.19.159.190/32 | 10.99.0.0/16, 10.99.0.2/32
```

Routes to 104.16.208.203/32 and 104.19.159.190/32 was not approved.

autoApprove in ACL looks like this
```
...
"autoApprovers": {
    "routes": {
      "10.99.0.0/16": [
        "tag:routers-vpn"
      ],
      "0.0.0.0/0": [
        "tag:internet-routers"
      ],
      "::/0": [
        "tag:internet-routers"
      ]
    },
    "exitNode": [
      "tag:exit-nodes"
    ]
},
...
```

### Expected Behavior

Have the routes auto-enabled from start
```
ID   | Hostname  | Approved                                                         | Available                                                        | Serving (Primary)
2414 | router-01 | 10.99.0.0/16, 10.99.0.2/32, 104.16.208.203/32, 104.19.159.190/32 | 10.99.0.0/16, 10.99.0.2/32, 104.16.208.203/32, 104.19.159.190/32 | 10.99.0.0/16, 10.99.0.2/32, 104.16.208.203/32, 104.19.159.190/32
```

### Steps To Reproduce

Config
```
---
server_url: https://hsc.example.org
listen_addr: 127.0.0.1:8080
metrics_listen_addr: 127.0.0.1:9090
grpc_listen_addr: 127.0.0.1:50443
grpc_allow_insecure: false

noise:
  private_key_path: /var/lib/headscale/noise_private.key

prefixes:
  v4: 100.64.0.0/10
  v6: fd7a:115c:a1e0::/48
  allocation: sequential

derp:
  server:
    enabled: false
    region_id: 999
    region_code: "headscale"
    region_name: "Headscale Embedded DERP"
    stun_listen_addr: "0.0.0.0:3478"
    private_key_path: /var/lib/headscale/derp_server_private.key
    automatically_add_embedded_derp_region: true
    ipv4: 1.2.3.4
    ipv6: 2001:db8::1
  urls:
    - https://controlplane.tailscale.com/derpmap/default
  paths: []
  auto_update_enabled: true
  update_frequency: 24h

disable_check_updates: true
ephemeral_node_inactivity_timeout: 30m

database:
  type: postgres
  gorm:
    prepare_stmt: true
    parameterized_queries: true
    skip_err_record_not_found: true
    slow_threshold: 1000

  postgres:
    host: localhost
    port: 5432
    name: headscale
    user: headscale
    pass: xxxxxxxxxx
    max_open_conns: 10
    max_idle_conns: 10
    conn_max_idle_time_secs: 3600

acme_url: https://acme-v02.api.letsencrypt.org/directory
acme_email: admin@example.org

tls_letsencrypt_hostname: ""
tls_letsencrypt_cache_dir: /var/lib/headscale/cache
tls_letsencrypt_challenge_type: HTTP-01
tls_letsencrypt_listen: ":http"
tls_cert_path: ""
tls_key_path: ""

log:
  format: text
  level: debug

policy:
  mode: file
  path: /etc/headscale/acl.hujson

dns:
  magic_dns: false
  base_domain: vpn

  nameservers:
    global:
      - 1.1.1.1
    split:
      {}
  search_domains: []
  extra_records: []

unix_socket: /var/run/headscale/headscale.sock
unix_socket_permission: "0770"

oidc:
  only_start_if_oidc_is_available: true
  issuer: https://issuer.example.org
  client_id: headscale
  client_secret: xxxxxxxxxx
  expiry: 1d
  use_expiry_from_token: false
  scope: ["openid", "profile", "email"]
  allowed_domains:
    - example.org

logtail:
  enabled: false

randomize_client_port: false
```

Policy
```
{
  "groups": {
    "group:users": [
      "user1@example.org",
      "user2@example.org"
    ],
    "group:exit-nodes": [
      "exit-node@"
    ],
    "group:internet-routers": [
      "router-01@",
      "router-02@"
    ],
    "group:routers-vpn": [
      "router-01@",
      "router-02@"
    ]
  },
  "tagOwners": {
    "tag:routers-vpn": [
      "group:routers-vpn"
    ],
    "tag:internet-routers": [
      "group:internet-routers"
    ],
    "tag:exit-nodes": [
      "group:exit-nodes"
    ]
  },
  "autoApprovers": {
    "routes": {
      "10.99.0.0/16": [
        "tag:routers-vpn"
      ],
      "0.0.0.0/0": [
        "tag:internet-routers"
      ],
      "::/0": [
        "tag:internet-routers"
      ]
    },
    "exitNode": [
      "tag:exit-nodes"
    ]
  },
  "hosts": {
    "vpn-dns": "10.99.0.2/32",
    "vpn-network": "10.99.0.0/16"
  },
  "acls": [
    {
      "action": "accept",
      "src": [
        "*"
      ],
      "dst": [
        "vpn-dns:53",
        "0.0.0.0:53",
        "group:routers-vpn:0"
      ]
    },
    {
      "action": "accept",
      "src": [
        "group:users"
      ],
      "dst": [
        "group:exit-nodes:0",
        "autogroup:internet:*"
      ]
    },
    {
      "action": "accept",
      "src": [
        "group:users"
      ],
      "dst": [
        "group:routers-vpn:0",
        "vpn-network:*",
        "104.16.208.203:*",
        "104.19.159.190:*"
      ]
    }
  ]
}
```

Tailscale
```
tailscale up --login-server https://hsc.example.org --hostname='router-01' --advertise-exit-node=false --accept-routes=false --accept-dns=false --snat-subnet-routes=true --advertise-tags='tag:routers-vpn,tag:internet-routers' --advertise-routes='10.99.0.0/16,104.16.208.203/32,104.19.159.190/32,10.99.0.2/32'
```

### Environment

```markdown
- OS: Ubuntu 24.04
- Headscale version: v0.26.0-beta.1
- Tailscale version: v1.82.5
```

### Runtime environment

- [x] Headscale is behind a (reverse) proxy
- [ ] Headscale runs in a container

### Debug information

Route management is not logged.
