### ISSUE TITLE
[Bug] SSH autogroup:nonroot does not permit non-root usernames

### ISSUE THREAD

**Issue by mitchplze** [juanfont/headscale#2645]
### Is this a support request?

- [x] This is not a support request

### Is there an existing issue for this?

- [x] I have searched the existing issues

### Current Behavior

With the following block:

```yaml
"ssh": [
    {
      "action": "accept",
      "src": ["tag:admin", "group:admin"],
      "dst": ["*"],
      "users": ["autogroup:nonroot", "root"]
    }
  ]
```

Despite `--ssh` being set and the user existing on the target system, admins are unable to SSH with the username `test` to the destination.

The error returned is: 

```
mitch@Mitchs-MacBook ~ % ssh test@100.123.123.123
tailscale: failed to evaluate SSH policyConnection closed by 100.123.123.123 port 22
```

When I explicitly add `"test"` to `users:`, it works as expected. 

```yaml
"ssh": [
    {
      "action": "accept",
      "src": ["tag:admin", "group:admin"],
      "dst": ["*"],
      "users": ["autogroup:nonroot", "root", "test"]
    }
  ]
```

### Expected Behavior

As per [Tailscale docs](https://tailscale.com/kb/1337/policy-syntax#users), the `autogroup:nonroot` group in an SSH ACL policy, should permit any username that is not `root` to login to the machine. This does not currently appear to be the case with Headscale `0.26.1`.

### Steps To Reproduce

As per above, create an SSH block permitting `autogroup:nonroot` and users will not be able to login.

### Environment

```markdown
- OS: Debian 12 via Docker
- Headscale version: 0.26.1
- Tailscale version: 1.81.1
```

### Runtime environment

- [x] Headscale is behind a (reverse) proxy
- [x] Headscale runs in a container

### Debug information

N/A
