### ISSUE TITLE
/metrics is accessible open wide

### ISSUE THREAD

**Issue by reynico** [juanfont/headscale#343]
Hi!

The `/metrics` endpoint is accessible open wide to the Internet with the default configuration:
```yaml
server_url: https://tailscale.dev:8080

# Address to listen to / bind to on the server
#
listen_addr: 0.0.0.0:8080
```

Note that `listen_addr` should be listening on `0.0.0.0` so the clients can authenticate to the server, but I think `/metrics` should be available only for the local network, either by listening on a different port or by a blocking rule.

Bonus points to make `/metrics` a toggleable endpoint!
