### ISSUE TITLE
Defining a derp server (and removing default ones) disables direct connection

### ISSUE THREAD

**Issue by Patralos** [juanfont/headscale#543]
Hi,

I have the problem, that as long as I keep the default derp configuration, I am using direct mode between nodes, visible in tailscale status.

As soon as I remove the official derp servers by removing the setting urls:
`urls: []`

All connections go over my relay, none of them is direct anymore.

My derp file looks like this:
```
regions:
  900:
    regionid: 900
    regioncode: Name
    regionname: Name
    nodes:
      - name: 900a
        regionid: 900
        hostname: url
```

Is this intended behavior? Is it possible to use direct connections while running a private relay?
