### ISSUE TITLE
Handle CORS headers and OPTIONS method for HTTP API

### ISSUE THREAD

**Issue by routerino** [juanfont/headscale#623]
**Bug description**

When trying to use a browser to generate API requests (like, hypothetically, if you're building a web frontend for headscale), the browser expects to to use CORS to determine if it can talk to the external server. The browser does this by the following:
* Sending a pre-flight `OPTIONS` request, expecting back a 204 response with the CORS headers attached
* Once the response is accepted, sending the real API request with all the data

For this to work, we need two things:
* The server (headscale) to generate CORS headers (and have it be configurable to set the domains appropriately)
* The server to accept `OPTIONS` requests without authorization.

**To Reproduce**
Generate a fetch request from a browser in a separate domain. Such as:

``` javascript
let apiKey = '<my api key>';
let url = 'https://<my headscale domain>/api/v1/machine';

window.fetch(url, {
    method: 'GET',
    headers: {
        Authorization: `Bearer ${apiKey}`
    }}).then((resp) => resp.json()).then(function (data) {console.log(data);}).catch(function (error) {console.log(error);});});
```

If no CORS headers are specified, you get this nice error in the browser console:
![image](https://user-images.githubusercontent.com/45954722/172862437-f64c47d2-8ae1-46b1-95ab-87123487c74e.png)

If you have the right headers (if you, for example, inject them with a reverse proxy) but the OPTIONS request is blocked by authorization, you get this nice error instead:
![image](https://user-images.githubusercontent.com/45954722/172862213-d8c060cf-eb58-4a4b-b486-e8dcf5942364.png)

Because the OPTIONS request is returning a 401 unauthorized when it shouldn't.

Both are not ideal. You can *fix* both with a reverse proxy, but you certainly shouldn't have to. The web server (gin?) should return OPTIONS with a 204 and be setting the CORS headers on all requests (and the CORS headers should be configurable).

**Context info**

These problems were fixed externally by routing through a Caddy reverse proxy using these matching settings:

```
@hs-options {
	host hs.<my-domain>
	method OPTIONS
}
@hs-other {
	host hs.<my-domain>
}
handle @hs-options {
	header {
		Access-Control-Allow-Origin https://<my-frontend-subdomain>
		Access-Control-Allow-Headers *
	}
	respond 204
}
handle @hs-other {
	reverse_proxy http://headscale:8080 {
		header_down Access-Control-Allow-Origin https://<my-frontend-subdomain>
		header_down Access-Control-Allow-Headers *
	}
}
```

**Comment by Mikle-Bond** [comment]
If you use [caddy-docker-proxy](https://github.com/lucaslorentz/caddy-docker-proxy), here's the same (mostly) config, done in labels:

```yaml
    labels:
      caddy: "headscale.${BASE_DOMAIN}"
      caddy.@hs-other.host: "headscale.${BASE_DOMAIN}"
      caddy.@hs-options.host: "headscale.${BASE_DOMAIN}"
      caddy.@hs-options.method: OPTIONS

      caddy.0_import: tlsdns

      caddy.1_handle: "@hs-options"
      caddy.1_handle.header.Access-Control-Allow-Origin: "https://ui.headscale.${BASE_DOMAIN}"
      caddy.1_handle.header.Access-Control-Allow-Headers: "*"
      caddy.1_handle.header.Access-Control-Allow-Methods: '"POST, GET, OPTIONS, DELETE"'
      caddy.1_handle.respond: "204"

      caddy.8_handle: /metrics
      caddy.8_handle.import: auth
      caddy.8_handle.reverse_proxy: "{{upstreams 9090}}"

      caddy.9_handle: "@hs-other"
      caddy.9_handle.reverse_proxy: "{{upstreams 80}}"
      caddy.9_handle.reverse_proxy.header_down_1: "Access-Control-Allow-Origin https://ui.headscale.${BASE_DOMAIN}"
      caddy.9_handle.reverse_proxy.header_down_2: "Access-Control-Allow-Headers *"
      caddy.9_handle.reverse_proxy.header_down_3: 'Access-Control-Allow-Methods "POST, GET, OPTIONS, DELETE"'
```

**Comment by deimjons** [comment]
Someone know how to config it for Traefik? 
I tryed to add next labels:

```
traefik.http.middlewares.headscale-cors.headers.customResponseHeaders.Access-Control-Allow-Origin: https://web.headscale.yourdomain.example
traefik.http.middlewares.headscale-cors.headers.customResponseHeaders.Access-Control-Allow-Methods: GET, POST, PUT, DELETE
traefik.http.middlewares.headscale-cors.headers.customResponseHeaders.Access-Control-Allow-Headers: Content-Type
```

Looks like the first part of the problem is solved, but I have a problem with 204 status code on the answer.. 

Looks like https://plugins.traefik.io/plugins/632b03d4eff06de33b092374/cors-preflight this plugin should help but I can't configure it properly, it shows me error "status code is smallest than minimum value: 100" 
(Issue with details opeend here: https://github.com/Medzoner/traefik-plugin-cors-preflight/issues/8)

**Comment by Mikle-Bond** [comment]
@deimjons 
Maybe try this plugin instead? https://plugins.traefik.io/plugins/628c9f0f108ecc83915d7771/replace-status-code

**Comment by deimjons** [comment]
@Mikle-Bond Thank you for your attention. I tried this plugin but it didn't help me. I don't know: I doing something wrong or the plugin just not working. 

I have added additional routes in labels:

```
      traefik.http.routers.headscale-options.rule: Host(`headscale.yourdomain.example/api/v1/apikey`) && Method(`OPTIONS`)
      traefik.http.routers.headscale-options.entrypoints: websecure
      traefik.http.routers.headscale-options.tls: true
      traefik.http.routers.headscale-options.tls.certresolver: prod
      traefik.http.routers.headscale-options.middlewares: replace-response-code@file  
```
also, I added a plugin  and middleware (like they show in the documentation example) in the configuration file of traefik: traefik.yaml

```
experimental:
  plugins:
    traefik-replace-response-code:
      moduleName: "github.com/pierre-verhaeghe/traefik-replace-response-code"
      version: "v0.2.0"

http:
  middlewares:
    replace-response-code:
      plugin:
        traefik-replace-response-code:
          inputCode: 401
          outputCode: 200
          removeBody: "true"
```

As a result, I have the same error:

> Access to fetch at 'https://headscale.yourdomain.example/api/v1/apikey' from origin 'https://admin.headscale.yourdomain.example' has been blocked by CORS policy: Response to preflight request doesn't pass access control check: It does not have HTTP ok status.
