### ISSUE TITLE
Container's embedded DERP only has STUN port

### ISSUE THREAD

**Issue by 1itt1eB0y** [juanfont/headscale#673]
config.yml
```yaml
server_url: https://*.com:8080
listen_addr: 0.0.0.0:8080
metrics_listen_addr: 0.0.0.0:19090
grpc_listen_addr: 0.0.0.0:50443
grpc_allow_insecure: false
private_key_path: /etc/headscale/private.key
ip_prefixes:
  - 10.10.0.0/16
derp:
  server:
    enabled: false
    region_id: 999
    region_code: "headscale"
    region_name: "Headscale Embedded DERP"
    stun_listen_addr: "0.0.0.0:44444"
  paths: ["/etc/headscale/derp.yaml"]
  auto_update_enabled: true
  update_frequency: 5m
disable_check_updates: false
ephemeral_node_inactivity_timeout: 30m
db_type: sqlite3
db_path: /etc/headscale/db.sqlite
tls_client_auth_mode: disabled
tls_cert_path: "/etc/headscale/*.com/fullchain1.pem"
tls_key_path: "/etc/headscale/*.com/privkey1.pem"
log_level: debug
acl_policy_path: ""
dns_config:
  nameservers:
    - 10.10.0.1
  domains: []
  magic_dns: false
  base_domain: lan
unix_socket: /var/run/headscale.sock
unix_socket_permission: "0770"
```

docker-compose.yml
```yaml
version: "3"
services:
  headscale:
    container_name: headscale
    restart: always
    environment:
      - TZ=UTC+8
      - GIN_MODE=release
    image: headscale/headscale:latest
    ports:
      - 8080:8080/tcp
      - 10.0.21.1:19090:19090/tcp
      - 44444:44444/udp
    volumes:
      - /root/docker/headscale/config:/etc/headscale/
    command:
      - headscale
      - serve
```

port status
![图片](https://user-images.githubusercontent.com/29831189/178110188-e768a8e9-d969-4187-af8a-d4545aa6049f.png)

STUN port is working. I didn't capture a screenshot but it can be found with nmap
