### ISSUE TITLE
tailscale client cannot register/login when setup headscale behind istio

### ISSUE THREAD

**Issue by kevin1sMe** [juanfont/headscale#851]
Headscale is a great project ! !

I face a problem when  **setup headscale behind istio ingress( reverse proxy)**.
When I try to login:
```bash
tailscale up --login-server=<https://headscale.example.com> --accept-routes=true --accept-dns=false
```
No responsed.

Look at envoy debug log:
```log
S11933942887229510821] request headers complete (end_stream=false):
':authority', 'headscale.example.com',
':path', '/ts2021'
':method', 'POST'
'user-agent', 'Go-http-client/1.1'
'content-length', '0'
'connection', 'upgrade'
'upgrade', 'tailscale-control-protocol'
'x-tailscale-handshake', 'ACkBAG.....'

...
2022-10-09T05:04:25.470382Z	debug	envoy connection	[C795] current connecting state: false
2022-10-09T05:04:25.470435Z	debug	envoy http	[C795][S11933942887229510821] Sending local reply with details upgrade_failed
2022-10-09T05:04:25.470458Z	debug	envoy http	[C795][S11933942887229510821] closing connection due to connection close header
```

Expect login succ.

**Context info**

**Comment by rjmalagon** [comment]
I had an issue with another reverse proxy (cloudflared), because it does not support upgrade a https connection to wss on same port/connection. I had to scrape that reverse proxy configuration.

Your reverse proxy configuration supports websocket upgrades?

**Comment by kevin1sMe** [comment]
> 

Yes . Istio's data plane is envoy.  [http/upgrades](https://www.envoyproxy.io/docs/envoy/latest/intro/arch_overview/http/upgrades)

**Comment by juanfont** [comment]
Are you still having this?

**Comment by clarkmcc** [comment]
@kevin1sMe sorry, didn't see the notification. Have you tried a TCP virtual service? Something along these lines?
```yaml
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: headscale.xxxx
spec:
  hosts:
  - headscale.headscale.svc.cluster.local
  gateways:
    - istio-ingress/xxx-gateway
    - mesh
  tcp:
  - match:
    - port: 8080
    route:
    - destination:
        host: headscale.headscale.svc.cluster.local
        port:
          number: 8080
```
